### ISSUE TITLE
Custom Field Types

### ISSUE THREAD

**Issue by PascalKleindienst** [PascalKleindienst/FormListGenerator#11]
add method to add custom field types to forms / lists

```php
class EditorField extends AbstractField {
 // ...
}
$form = new FormGenerator();
$form->addFieldType('editor', EditorField::class); // identifier, Class which inherits AbstractFieldClass
```

```yaml
fields:
    email_signature:
        label: Email Signature
        type: editor
```
