### ISSUE TITLE
Dot-Notation

### ISSUE THREAD

**Issue by PascalKleindienst** [PascalKleindienst/FormListGenerator#7]
Allow for dot notation in yaml files for columns and field identifiers

Example:
```yaml
recursive.test:
    label: Recursive Test
    type: text
```

with the following data
```php
$data = [
    'recursive' => [
        'test' => 'Foo',
        'bar' => 'Bar',
    ]
];
```
